parseArgs: fix 32/64 bit compatiblity in formatstrings
Trying to print int64_t with "%ld" and uint64_t with "%lu" results in a
compiler error:

error: format '%lu' expects argument of type 'long unsigned int', but argument N has type 'uint64_t' {aka 'long long unsigned int'}

when cross built for ARM 32 bit.

The correct way to print these types is with

  #include <cinttypes>
  ...
  printf("%" PRId64 "\n", var);

instead of "%ld" and

  printf("%" PRIu64 "\n", var);

instead of "%lu".

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>